### ISSUE TITLE
Revisar configuración de exoneraciones y crear propuesta de UI

### ISSUE THREAD

**Issue by WhiteTiger08** [odoocr/l10n_cr#11]

**Comment by charlit02390** [comment]
<img width="968" alt="Screen Shot 2019-06-05 at 3 35 30 PM" src="https://user-images.githubusercontent.com/15387828/58992534-58779c00-87a8-11e9-9439-91d4433874b4.png">
Esta es la actual UI que existe dentro de odoo y se crea una exoneracion general, pero se puede aplicar por linea en la facturacion pero se aplica solo en el xml no se aplica a nivel contable de odoo (investigar como se puede realizar), la idea es crear un referencia por cliente y que solo se muestre las exoneraciones que posee dicho cliente y no todas las que posea el sistema en ese momento, hay muchas dudas al respecto a esto por parte mia porque los documentos que poseo de exoneraciones no detallan la informacion que hacienda solicita

**Comment by charlit02390** [comment]
https://github.com/odoocr/l10n_cr/pull/77
