### ISSUE TITLE
Implementar IVA devuelto

### ISSUE THREAD

**Issue by PlainGreed** [odoocr/l10n_cr#122]
###### Impacted versions:
* Todas

###### Steps to reproduce:
*  

###### Current behavior:
* No se maneja IVA devuelto, actualmente debe hacerse un asiento manual.

###### Expected behavior:
* Odoo debería hacerlo automáticamente si es un servicio que lo hace identificando el modo de pago.

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by TheCloneMaster** [comment]
ya hay un primer intento un poco burdo en action_invoice_open...
se aceptan sugerencias y PRs para mejorar el proceso....

**Comment by jartavia05** [comment]
@TheCloneMaster, ya lo tengo implementado y lo he probado por casi mes con un cliente, sin problemas. Voy a preparar el PR.

**Comment by keadanis** [comment]
Resuelto con https://github.com/odoocr/l10n_cr/pull/267

**Comment by TheCloneMaster** [comment]
Hola, disculpas por no responder a tiempo, pero lo del IVA devuelto estaba
ya a medias en el código, pero de una forma diferente...

Se había implementado por medio de un "producto" definido como IVA
Devuelto, de forma que en las características del producto se podía asignar
la cuenta contable a usar para acumular esa devolución (sin tener que
agregar campos nuevos).  Estaba basado en la idea aplicada por otros
módulos para aplicar "Descuentos Globales", que me parecieron muy limpios
precisamente porque no tienen que recurrir a modificar código base ni
montos base de Odoo...

A esta otra implementación le veo varios problemas, pues modifica varios
mecanismos de cálculos base de Odoo, como montos globales de facturas, los
asientos asociados, etc...., lo cual hace que a futuro se vuelva más
complicado de mantener... además de que requiere más de cuatro veces la
cantidad de líneas de código que la opción original.

Podemos conversar al respecto para hacer un PR que aproveche lo mejor de
ambas opciones, y nos deje la mejor solución posible?

Saludos,
-Mario
