### ISSUE TITLE
Manejar la fecha de caducidad del certificado de Hacienda

### ISSUE THREAD

**Issue by PlainGreed** [odoocr/l10n_cr#125]
###### Impacted versions:
*  Todas

###### Steps to reproduce:
* 

###### Current behavior:
* Actualmente no se revisa esa fecha de caducidad. Si vence el certificado, todos los documentos enviados a Hacienda serán rechazados 

###### Expected behavior:
* Odoo debería manejar esa fecha y mostrar alertas cuando la fecha esté próxima a cumplirse para que el encargado genere un nuevo certificado.

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by TheCloneMaster** [comment]
creo k lo más sencillo sería al cargar el certificado, extraer la fecha de vencimiento y almacenar en un campo, y luego tener un cron que corra una vez por semana (o algún otro período) y avise cuando algún certificado esté cerca de vencer....

**Comment by norubo** [comment]
Hi, check out this pull request

**#209**  [ADD] Search for tax according to the CAByS code of the product and Expiration date of the Ministerio de Hacienda certificate

**Comment by keadanis** [comment]
Resuelto con el PR   https://github.com/odoocr/l10n_cr/pull/252
