### ISSUE TITLE
Al importar el impuesto sobreescribe el nombre y Incluir en el precio

### ISSUE THREAD

**Issue by EstebanMonge** [odoocr/l10n_cr#132]
###### Impacted versions:
* Todas

###### Steps to reproduce:
* Al actualizar las bases de datos se sobre escribe el nombre y el check de Incluir en el precio

###### Current behavior:
* Se sobre escribe el nombre y el check de Incluir en el precio

###### Expected behavior:
* Si el impuesto existe no sobre escribir valores

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by EstebanMonge** [comment]
Ademas cuando se importan productos en la función se indica que existen dos impuestos iguales, debería diferenciarse el IVA de compra del IVA de venta

**Comment by EstebanMonge** [comment]
El PR # 35 soluciona este problema

**Comment by PlainGreed** [comment]
¿Esto ya se solucionó?

**Comment by EstebanMonge** [comment]
Si resuelto
