### ISSUE TITLE
Error al imprimir cuenta en POS

### ISSUE THREAD

**Issue by lmoram** [odoocr/l10n_cr#147]
###### Impacted versions:
12
###### Current behavior:
A la hora de imprimir una cuenta en el POS genera error ya que trata de cargar clave y consecutivo.
###### Expected behavior:
El sistema debe omitir la clave y consecutivo cuando se imprime una cuenta en el POS

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by EstebanMonge** [comment]
`
<t t-if="order.attributes.number_electronic">
            <div class="pos-center-align">
                  Clave: <br/>
                  <t t-esc="order.attributes.number_electronic.substring(0,25)"/><br/>
                  <t t-esc="order.attributes.number_electronic.substring(25,50)"/>
            </div>
            <div class="pos-center-align">
                  Consecutivo: <br/>
                  <t t-esc="order.attributes.number_electronic.substring(21,41)"/>
            </div>
           </t>
`
cr_electronic_invoice_pos/static/src/xml
Posible solución.
