### ISSUE TITLE
Definir e implementar el método de generación y validación de los XML para facturación electrónica

### ISSUE THREAD

**Issue by WhiteTiger08** [odoocr/l10n_cr#15]
**Impacted versions:**
10.0, 11.0 y 12.0

**Current behavior:**
Actualmente se está utilizando un stringbuilder y no se valida el XML antes de enviarlo a hacienda

**Expected behavior:**
Utilizar una librería o metodología que permita crear los XMLs de manera más estructurada y validarlos con los XSDs correspondientes.

**Comment by PlainGreed** [comment]
Se desestimó esta tarea por el momento
