### ISSUE TITLE
problemas con modulo Costa Rica currency adapter

### ISSUE THREAD

**Issue by crodriguez82** [odoocr/l10n_cr#150]
###### Impacted versions:
* 

cuando corre el servicio brinda el siguiente error en odoo11

ValueError: <class 'ValueError'>: "unknown url type: 'XMLSchema.dtd'" while evaluating
'model._cron_update()'

###### Steps to reproduce:
* 

###### Current behavior:
*

###### Expected behavior:
*

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by PlainGreed** [comment]
Hola, el BCCR cambió el Webservice. Por el momento solo se ha cambiado para la version 12.0.
