### ISSUE TITLE
Medios de pago en POS

### ISSUE THREAD

**Issue by keadanis** [odoocr/l10n_cr#160]
###### Impacted versions:
* 12

###### Steps to reproduce:
* Facturar en POS usando diferentes métodos de pago

###### Current behavior:
* A pesar de escoger tarjeta, contado o ambos métodos de pago al facturar en POS, en el XML únicamente se refleja un método de pago, el cual siempre es el de código 01

###### Expected behavior:
* Se debe incluir en el XML el código de el o los métodos de pago correctos, con un máximo de 4 según la estructura de la versión 4.3

**Comment by PlainGreed** [comment]
@TheCloneMaster @EstebanMonge 
¿pueden revisar esto?

**Comment by EstebanMonge** [comment]
Hola, si voy a ver

**Comment by keadanis** [comment]
Resuelto
