### ISSUE TITLE
Fecha de Factura Referencia de rectificadas en False, genera error en generate_and_send_invoice

### ISSUE THREAD

**Issue by syscon3** [odoocr/l10n_cr#168]
###### Impacted versions:
* 12

###### Steps to reproduce:
* Generar Factura Rectificativa de Cliente a partir de una Factura Existente

###### Current behavior:
*Se establece el TAG **InformacionReferencia -> FechaEmision**  en False cuando se genera el XML de la Nota de Credito o rectificada, por tomar el campo **date_issueance** de la factura referenciada. Este campo no tiene valor establecido.

ERROR: 
  File "/home/laterraza_2/odoo-12/odoo/addons/cr_electronic_invoice/models/account_invoice.py", line 901, in _send_invoices_to_hacienda
    self.generate_and_send_invoices(invoices)
  File "/home/laterraza_2/odoo-12/odoo/addons/cr_electronic_invoice/models/account_invoice.py", line 1211, in generate_and_send_invoices
    fecha_emision_referencia, codigo_referencia, razon_referencia)
  File "/home/laterraza_2/odoo-12/odoo/addons/cr_electronic_invoice/models/api_facturae.py", line 633, in gen_xml_v43
    sb.Append('<FechaEmision>' + fecha_emision_referencia + '</FechaEmision>')
ValueError: <class 'TypeError'>: "Can't convert 'bool' object to str implicitly" while evaluating
'model._send_invoices_to_hacienda()'

###### Expected behavior:
*Establecer el TAG **InformacionReferencia -> FechaEmision** del documento XML de referencia con el campo **date_invoice** de la factura referenciada

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by syscon3** [comment]
diff --git a/cr_electronic_invoice/models/account_invoice.py b/cr_electronic_invoice/models/account_invoice.py
index c2922b9..14123c7 100644
--- a/cr_electronic_invoice/models/account_invoice.py
+++ b/cr_electronic_invoice/models/account_invoice.py
@@ -960,7 +960,7 @@
                 if inv.invoice_id and inv.reference_code_id and inv.reference_document_id:
                     if inv.invoice_id.number_electronic:
                         numero_documento_referencia = inv.invoice_id.number_electronic
-                        fecha_emision_referencia = inv.invoice_id.date_issuance
+                        fecha_emision_referencia = inv.invoice_id.date_invoice.strftime("%Y-%m-%d") + "T12:00:00-06:00"
                     else:
                         numero_documento_referencia = inv.invoice_id and re.sub('[^0-9]+', '', inv.invoice_id.sequence).rjust(50, '0') or '0000000'
                         date_invoice = datetime.datetime.strptime(inv.invoice_id and inv.invoice_id.date_invoice or '2018-08-30', "%Y-%m-%d")

**Comment by syscon3** [comment]
#169 seria el pull request que soluciona el problema

**Comment by PlainGreed** [comment]
¿Esto ya fue solucionado?

**Comment by keadanis** [comment]
Solucionado con el PR    https://github.com/odoocr/l10n_cr/pull/169
