### ISSUE TITLE
Crear XML para actualizar unidades de medida y agregar las faltantes para 4.3

### ISSUE THREAD

**Issue by WhiteTiger08** [odoocr/l10n_cr#17]
Impacted versions:
12.0 

Steps to reproduce:

Current behavior:
Se eliminó el CSV de unidades de medidas

Expected behavior:
Que actualice las unidades de medida con el código de hacienda al momento de instalación. Esto para prevenir que al habilitarlas de problemas con módulo de facturación.

Video/Screenshot link (optional):

**Comment by josuecocoman** [comment]
working on it today

**Comment by PlainGreed** [comment]
Arreglado en PR #59
