### ISSUE TITLE
Código de método de pago POS en el XML

### ISSUE THREAD

**Issue by keadanis** [odoocr/l10n_cr#174]
###### Impacted versions:
* 12

###### Steps to reproduce:
* Al facturar en POS ya sea por tarjeta o cualquier otro método de pago

###### Current behavior:
* En el XML el código del método de pago siempre es 01

###### Expected behavior:
* En el XML debe poner el código del método de pago utilizado

**Comment by EstebanMonge** [comment]
Duplicado con #160
