### ISSUE TITLE
Errores de aceptación por longitud de actividad económica inválida

### ISSUE THREAD

**Issue by EstebanMonge** [odoocr/l10n_cr#176]
###### Impacted versions:
* Todas

###### Steps to reproduce:
* Las actividades económicas que vienen de Hacienda con menos de seis digitos son rechazadas

###### Current behavior:
* El documento es rechazado

###### Expected behavior:
* Rellenar con 0s las actividades económicas con menos de 6 caracteres y que el documento sea aceptado

**Comment by keadanis** [comment]
Resuelto con el PR    https://github.com/odoocr/l10n_cr/pull/189/commits/374f4b3b4c88324392b6af13a77ebbc8ae82d047
