### ISSUE TITLE
Actividad económica en producto

### ISSUE THREAD

**Issue by keadanis** [odoocr/l10n_cr#188]
###### Impacted versions:
* Todas

###### Steps to reproduce:
* Crear un producto y seleccionar la actividad económica.

###### Current behavior:
* Al hacer click en seleccionar la actividad económica se despliega la lista de todas las actividades económicas.

###### Expected behavior:
* Al hacer click en seleccionar la actividad económica debe filtrarse por las actividades económicas activas de la compañía.

**Comment by jaullo** [comment]
Asociada a #194 es el mismo comportamiento para todos los filtros del tipo actividad económica

**Comment by keadanis** [comment]
Resuelto
