### ISSUE TITLE
Línea única Otros Cargos

### ISSUE THREAD

**Issue by jaullo** [odoocr/l10n_cr#195]
###### Impacted versions:
13

###### Steps to reproduce:
1. Crear una nueva factura
2. Seleccionar como producto Otros Cargos
3. No agregar ningún otro producto

###### Current behavior:
El xml se genera erroneamente pues busca la existencia del TAG DetalleServicio el cual no existe

###### Expected behavior:
El xml se genera correctamente y por tanto es aprobado por hacienda

**Comment by syscon3** [comment]
Tengo el mismo problema y lo voy a revisar.. mi pregunta es si se debe generar la etiqueta vacia o no se debe agregar la etiqueta ?
A mi me aparece asi.

\<MedioPago>01\</MedioPago>
**\<DetalleServicio/\>**
\<OtrosCargos>
    \<TipoDocumento>Mouse001\</TipoDocumento>
    \<Detalle>Otros cargos\</Detalle>
    \<MontoCargo>20.34\</MontoCargo>
\</OtrosCargos>

Error: 
The content of element 'DetalleServicio' is not complete. One of '{\"https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronica\":LineaDetalle}' is expected."", 2, 1365 ]

Segun el anexo:
Tipo complejo que agrupa las líneas del detalle.
Es de carácter obligatorio cuando el comprobante
incorpore al menos una línea de un producto o servicio.

deberia ir sin el tag por lo que dice ahi.

Confirmame eso y lo veo en estos dias.

Saludos.

**Comment by syscon3** [comment]
Solucionado en PR #240
