### ISSUE TITLE
Nota Crédito Reverse Move Error

### ISSUE THREAD

**Issue by jaullo** [odoocr/l10n_cr#196]
###### Impacted versions:
13

###### Steps to reproduce:
1. Ingresar a una factura que se desee rectificar
2. Seleccionar Agregar Factura Rectificativa
3. Completar los datos del wizard y validar

###### Current behavior:
Genera un error TypeError: _reverse_moves() got an unexpected keyword argument 'invoice_date'

###### Expected behavior:
La nota de crédito se genera correctamente

**Comment by ivanporras** [comment]
@jaullo lograste corregir este error?

**Comment by ivanporras** [comment]
@jaullo @TheCloneMaster  acabo de hacer un PR que corrige este problema.

**Comment by keadanis** [comment]
corregido en el PR    https://github.com/odoocr/l10n_cr/pull/214/commits/8e5f77a0a5fab35320130f917c0776d4a3ef572c
