### ISSUE TITLE
Problemas de redondeo en odoo 11

### ISSUE THREAD

**Issue by EstebanMonge** [odoocr/l10n_cr#20]
Impacted versions:
11 y 12

Steps to reproduce:
El redondeo en los productos con impuestos da errores

Current behavior:
El tiquete se rechaza porque se redondea a mas de cinco números

Expected behavior:
El tiquete redondee a dos decimales

Video/Screenshot link (optional):

**Comment by EstebanMonge** [comment]
Cambiar las líneas:

                descuento = round((line.qty * line.price_unit)-line.price_subtotal,2) or 0
                natu_descuento = 'Descuento Comercial'

Y estas:

 payload['total_descuentos'] = round(base_total - amount_untaxed, 2)

**Comment by PlainGreed** [comment]
¿Esto es para el POS o para facturación?

**Comment by randall-vx** [comment]
POS.

**Comment by EstebanMonge** [comment]
Esto se arregló en el pull request #25
