### ISSUE TITLE
Error en xmlsig al querer firmar el XML

### ISSUE THREAD

**Issue by syscon3** [odoocr/l10n_cr#239]
###### Impacted versions:
* Odoo y l10n_cr 12.0 con xmlsig 0.1.5

###### Steps to reproduce:
* Hacer una factura y esperar el proceso de generacon del XML con xmlsig version 0.1.5

###### Current behavior:
* ValueError: <class 'AttributeError'>: "module 'xmlsig.utils' has no attribute 'OID_NAMES'" while evaluating

###### Expected behavior:
* 

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by syscon3** [comment]
Probe instalar la version 0.1.3 de xmlsig como vi en un issue anterior y se firma correctamente el XML

**Comment by syscon3** [comment]
Solucionado en PR #240

**Comment by keadanis** [comment]
Solucionado en PR   https://github.com/odoocr/l10n_cr/pull/240/commits/87a9de47841ef5c8ab474936d3eaf3c9bfcd9400
