### ISSUE TITLE
Error al crear multi-compañias con la misma cedula Fisica/Juridica. 

### ISSUE THREAD

**Issue by jartavia05** [odoocr/l10n_cr#246]
###### Impacted versions:
* 12

###### Steps to reproduce:
* Crear una nueva compañía: Compañía B.
* En la Compañía B asignar la misma cedula fisica/juridica de una compañía existente (Compañía A). 
* Consultar Actividad económica en Compañía B. 

###### Current behavior:
* Cuando se crea una segunda compañia (Compañía B) que utiliza la misma cedula que una compañía existente (Compañía A) y se consulta la actividad económica se genera un error, debido a que el método de consultar actividad económica asigna el nombre obtenido al nombre de la compañía. 
* En Odoo el nombre de la compañía debe ser único por lo cual se genera el error al crear la segunda Compañía B con la misma cedula juridica, porque esta asignando un nombre que ya existe.

###### Expected behavior:
* El nombre de la compañía debe ser único
  * Compañía A
  * Compañía B

* Un campo adicional para asignar el nombre obtenido en la consulta de la actividad economica, y usarlo en la creación del XML. Como sugerencia el campo podría ser: "Nombre Legal" 

###### Video/Screenshot link (optional):
![Screen Shot 2021-07-07 at 12 24 43 PM](https://user-images.githubusercontent.com/8932312/124810665-d629ab00-df1e-11eb-86d1-090a80621dfb.jpg)
 

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by syscon3** [comment]
**legal_name** seria un buen nombre

**Comment by jartavia05** [comment]
issue fixed with the commit 06c6f122d73407f45f6b99dece9a28ab3830fd81
