### ISSUE TITLE
Ajuste en modulo de res_currency_cr_adapter

### ISSUE THREAD

**Issue by BetaTechCR** [odoocr/l10n_cr#277]
###### Impacted versions:

Presenta problemas el modulo cuando no tiene al menos un registro en la tabla de tazas

###### Steps to reproduce:

Se instala el modulo en Odoo14 
Se configura el usuario de BCCR 
Se ingresa a la moneda USD 
Al actualizar da un error.

###### Current behavior:

El modelo de res_currency.py no tiene una validación si no existen datos en la tabla, por lo tanto al calculas las fechas da un error.

###### Expected behavior:

Se espera que al menos el primer registro lo obtenga del día actual y logre realizar el primer registro , posteriormente si estos no se mantienen actualizados la función de action_create_missing_exchange_rates debería poder recrear los días faltantes, por lo tanto se realiza una corrección en el código para que logre crear los datos en la base de datos: 

La variable de last_day debería de estar seteada con el día siguiente, ya que el BCCR  no tiene registros para ese día únicamente obtiene el día actual y al hacer la resta con el first_day para obtener el rango este dará correctamente el numero de días faltantes en la tabla:

res_currency.py: linea 35 a 44

        today = datetime.date.today()
        last_day = today + datetime.timedelta(days=1)

        first_day = currency_rate_obj.search([
            ('company_id', '=', self.env.user.company_id.id),
            ('currency_id', '=', self.id)
        ], limit=1, order='name asc')

        if not first_day:
            first_day = today

###### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/75415697/154332168-44c71147-ff1e-4e6d-a12b-f5830dc152f5.png)

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by ruiznorlan** [comment]
Hello, the topic will start to be validated, this can be fixed as follows (see image), when the correction be done in the repository, we link the issue in the PR

Could you please try the following code and tell us if the behavior is as expected?

![action_create_missing_exchange_rates](https://user-images.githubusercontent.com/95722875/158080865-f395b244-bef2-485d-b4c1-09d9db5452e9.png)

**Comment by ruiznorlan** [comment]
It's going to be corrected in the next PR

https://github.com/odoocr/l10n_cr/pull/281

Thanks for the report!
