### ISSUE TITLE
[16.0] CREAR RAMA 16.0 

### ISSUE THREAD

**Issue by ivanporras** [odoocr/l10n_cr#332]
###### Impacted versions:
* 16.0 

###### Steps to reproduce:
* Crear nueva rama para la version 16.0 por favor. Gracias de antemano!

###### Current behavior:
*

###### Expected behavior:
*

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by EstebanMonge** [comment]
Listo
