### ISSUE TITLE
Configuración manual al instalar

### ISSUE THREAD

**Issue by TheCloneMaster** [odoocr/l10n_cr#41]
Impacted versions: All

Current behavior:
Los siguientes ajustes se deben hacer actualmente de forma manual al instalar:
Activar secuencia de ND en diarios de Venta / Compra
Formato de las secuencias de los diarios de Venta / Compra (largo 10, sin ajustes por año, sin prefijo)
Ajustar el Tipo Impuesto al impuesto de ventas/compras

Expected behavior:
Se deberían configurar automáticamente al instalar, o documentar los que se deben hacer de forma manual

**Comment by PlainGreed** [comment]
Esto ya no aplica

**Comment by EstebanMonge** [comment]
Ya no aplica se cierra
