### ISSUE TITLE
Error Calculo de Descuentos

### ISSUE THREAD

**Issue by jaullo** [odoocr/l10n_cr#43]
Impacted versions: 12

Steps to reproduce:
Add a product line, set 5% discount and move to invoice validation.

Current behavior:
 MH retorna error "rechazado", dado que inicialmente se calcula price con descuento y luego nuevamente en otra linea se vuelve a calcular descuento sobre el monto anterior

Expected behavior:
Solo se calcula el descuento una vez, MH retorna aceptado

Video/Screenshot link (optional):

**Comment by TheCloneMaster** [comment]
Resuelto!
