### ISSUE TITLE
El CSV de barrios y los nombres contiene caracteres invalido

### ISSUE THREAD

**Issue by brocoloco** [odoocr/l10n_cr#55]
Impacted versions: 12.0
Steps to reproduce:
1. Instalar el módulo l10n_cr_country_codes
2. Abrir el archivo res.country.neighborhood.csv 
3. Ver la linea  8 donde dice "neighborhood_Otoya._Carmen_San José_SJ"

Problema:
Al tener un "punto" en el medio del nombre que usamos como ID va a causar un error de interpretacion al Odoo donde va a pensar que tiene una parte que indica el nombre del modulo donde proviene y luego el nombre del ID. Esto es un problema muy grave ya que si en un se necesita hacer referencia del barrio en un XML, este no se podrá encontrar. Igualmente para la migracion de CSV a XML no va a ser posible.

Se puede observar este problema en la tabla ir_model_data donde se muestran todos los valores que Odoo carga de CSV y XML y verá que los que tienen ese error aparece que modulo a que pertenecen no es "ln10_cr_country_codes", sino "neighborhood_Otoya". 
 
Otro problema es el uso de letras con acentos como "é" de San José y " " espacios para los "ID". Todos los distritos, cantones y barrios tienen ese problema y no es recomendado.

**Comment by randall-vx** [comment]
+1

**Comment by randall-vx** [comment]
Excelente. Eso se ve en el test de CI. Revisen el test N. 27.3

**Comment by brocoloco** [comment]
Donde está eso del test N 27.3? Como se ve eso (perdone mi ignorancia)

**Comment by randall-vx** [comment]
https://travis-ci.com/odoocr/l10n_cr

**Comment by brocoloco** [comment]
Bueno yo arreglé este problema corrigiendo los CSV y los pasé a XML. Aproveché y modifiqué las provincias a que no haga referencia al ln10_cr original que viene con el odoo. Sin embargo se da el problema de que el módulo l10n_cr_country_codes no va a poderse instalar para aquellas personas que ya cuentan con una DB donde ya instalaron el mismo módulo con los CSV anteriores. Esto por la dependencia que tiene y de los errores en el nombre del ID como se menciona en este issue. 

La pregunta es si estarán interesados a resolver el problema utilizando los XML que están en mi repositorio (no he hecho el PR) y quebrar los DB existentes (que tienen el problema) o prefieren dejar el problema como está? Hacer un script de migración no es fácil ya que se tiene que corregir a puro SQL los 540+ IDs que tienen el "punto" en el nombre. También está pendiente incluir el cambio de no utilizar letras con acentos (tildes) ni espacios en el nombre.

Yo quiero resolver este problema, pero necesito saber qué opina los encargados del odoocr.

**Comment by randall-vx** [comment]
Haga el PR. Eso se puede corregir con un script de actualización. Viendo el DIFF cualquiera en el grupo puede resolverlo.
