### ISSUE TITLE
Migrar módulos de EDI en OCA

### ISSUE THREAD

**Issue by WhiteTiger08** [odoocr/l10n_cr#7]
La importación de XMLs se basan en la arquitectura de OCA utilizado en Europa (https://github.com/OCA/edi), aun no están migrados los módulos base. 

- [ ] account_invoice_import
- [ ] base_business_document_import

**Comment by PlainGreed** [comment]
Listo, se incorporaron esos módulos dentro de FE por mientras OCA los publica en 12.0
